[src] Fix AdvancedTimer logs
sofa-framework/BeamAdapter pull request #20
Opened 2022-07-11 22:59 UTC by epernod

Some `AdvancedTimer` stepBegin/stepEnd had spelling inconsistencies

2022-07-12 00:08 UTC, fredroy requested changes

2022-07-12 00:08 UTC, fredroy commented on src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
> +    AdvancedTimer::stepBegin("AdaptiveBeamMapping_Apply");
Could have used ScopedAdvancedTimer here too no ?

2022-07-12 00:08 UTC, fredroy commented on src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
> +    AdvancedTimer::stepBegin("AdaptiveBeamMapping_Apply");
and the next other AdvancedTimers too...

2022-07-12 06:50 UTC, alxbilger requested changes
I also agree to prefer `ScopedAdvancedTimer` over `AdvancedTimers`

2022-07-12 06:50 UTC, alxbilger commented on src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
> +    ScopedAdvancedTimer timer("AdaptiveBeamForceFieldAndMass_addDForce");
I am not sure that this timer is relevant. It will be repeated many times depending on the number of iterations of the conjugate gradient.

2022-07-12 12:53 UTC, alxbilger approved these changes

2022-07-14 00:24 UTC, fredroy approved these changes

2022-07-14 00:48 UTC, merged