Fix draw methods in components
sofa-framework/BeamAdapter pull request #27
Opened 2022-07-19 12:56 UTC by epernod

- Some restoreState were missing
- Some methods were totally empty
- Others were still using direct gl methods

2022-07-19 13:44 UTC, alxbilger requested changes
Only minor comments

2022-07-19 13:48 UTC, epernod commented on src/BeamAdapter/component/engine/WireRestShape.inl
> +    vparams->drawTool()->drawPoints(points, 10, sofa::type::RGBAColor(1, 0.5, 0.5, 1));
not sure the type is compatible. Will check.

2022-07-19 13:53 UTC, epernod commented on src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
> +            colors.emplace_back(0.0f, 1.0f, 1.0f, 1.0f);
this might create a type cast warning, I think m_projected[i] is a bool. 
II prefer to keep the if / else but I could set red and ... yellow?

2022-07-19 13:57 UTC, alxbilger commented on src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
> +            colors.emplace_back(0.0f, 1.0f, 1.0f, 1.0f);
There would be an implicit type conversion from `bool` to `float`. But it's not a warning. It's a common practice in branchless programming. Here I agree that you can keep the branch and use red and yellow instead.

2022-08-02 06:29 UTC, fredroy commented on src/BeamAdapter/component/engine/WireRestShape.inl
> +    vparams->drawTool()->drawPoints(points, 10, sofa::type::RGBAColor(1, 0.5, 0.5, 1));
at least, it wont be compatible if DataTypes is on float anyway so I guess it is better to let it like that

2022-08-02 06:30 UTC, fredroy approved these changes

2022-08-02 06:31 UTC, merged