[component] Factorize BeamSection structure
sofa-framework/BeamAdapter pull request #42
Opened 2022-08-04 22:26 UTC by epernod

2022-08-05 00:01 UTC, fredroy requested changes

2022-08-05 00:01 UTC, fredroy commented on src/BeamAdapter/utils/BeamSection.h
> +#include <sofa/defaulttype/SolidTypes.h>
```suggestion
```
I dont see anything using SoldTypes here ? 🤔

2022-08-05 00:01 UTC, fredroy commented on src/BeamAdapter/utils/BeamSection.h
> +} // namespace sofa::BeamAdapter
```suggestion
} // namespace sofa::beamAdapter
```

2022-08-05 07:10 UTC, epernod commented on src/BeamAdapter/utils/BeamSection.h
> +#include <sofa/defaulttype/SolidTypes.h>
indeed

2022-08-10 03:43 UTC, fredroy approved these changes

2022-08-10 03:43 UTC, merged